### ISSUE TITLE
App freezes after rebuilding

### ISSUE THREAD

**Issue by tylerwithpin** [PhilDL/remix-gospel-stack#103]
Thanks for making this stack! It's been very helpful when trying to replicate something similar for our repo.

I was running the remix-gospel-stack locally with the `pnpm run dev --filter=@remix-gospel-stack/remix-app` command, and I noticed that after hot rebuilding the app no longer seemed to work. My initial and subsequent requests to localhost:3000 worked fine, but once I made a change to any of the relevant files and remix rebuilt, further requests to localhost:3000 would never finish loading. Have you seen this on your end? I don't know if it matters, but I did update the `@remix-run/dev` dependency to `^2.2.0` instead of the previous `^2.0.0`.

**Comment by PhilDL** [comment]
Hi, I tried it on a brand new `pnpm create remix@latest --init-script --install --template https://github.com/PhilDL/remix-gospel-stack` and I didn't have that problem.

All remix packages in version "^2.3.1" on my end.

This is my setup:

```bash
▶ npx envinfo --system --binaries

  System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 98.83 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: 8.12.0 - ~/Library/pnpm/pnpm
```

Could you run `npx envinfo --system --binaries` so we know a little bit more ? Also Do you have to CTRL-C to get out ?
