### ISSUE TITLE
👋👋👋

### ISSUE THREAD

**Issue by barbinbrad** [PhilDL/remix-gospel-stack#12]
Hi Phil, sorry to cold message you like this. I didn't know of another way to get in touch with you. I've started working on a side-project that I plan to open-source. It's an ERP system built with Remix.

I was wondering if you'd be willing to give me some advice. I see you work on both Odoo and Remix, so I figure you're more qualified than anyone. 

Thanks either way.

Brad Barbin

**Comment by PhilDL** [comment]
Hi Brad, I would be happy to chat, you can contact me on Twitter [@_philDL](https://twitter.com/_philDL) with direct messages.
