### ISSUE TITLE
remix: Permission denied error

### ISSUE THREAD

**Issue by Clee681** [PhilDL/remix-gospel-stack#23]
Thanks for putting this together! I'm hitting an issue where the `remix` cli doesn't have the executable bit set and therefore is causing a "Permission denied error"

```
remix build

sh: 1: remix: Permission denied
```

```
# ls -lah ./node_modules/@remix-run/dev/dist/cli.js
-rw-r--r-- 1 root root 550 Apr 25 16:22 ./node_modules/@remix-run/dev/dist/cli.js
```

**Comment by PhilDL** [comment]
Hello, 

Are you running commands from the root of your monorepo through `pnpm run build` or differently ?
Also, could you share an example repo that I could pull and test ?
