### ISSUE TITLE
troubles trying to deploy monorepro with pnpm with dockerfile and dokku

### ISSUE THREAD

**Issue by Jarrodsz** [PhilDL/remix-gospel-stack#57]
Before using this mono repro I had a working Dockerfile and did a git push dokku master. 
That way it would spin up a dokku deployment using the Dockerfile in the root of the project.

Since I switched to pnpm I have not been able to figure out the correct way to deploy, even using gpt4 ( no phun intended ) i tryed to find the correct methodology to deploy my apps.

Even while its a monorepro im still very used to cd to the /apps/myapp folder and do a pnpm dev 
The same goes for deployments. I would do a ```git push dokku master``` which would initiate the deployment, perhaps that is out of the scope of this repro and my question but deploying isent working at all.

This was my working Dockerfile:
https://gist.github.com/Jarrodsz/22ddc163d1cd8c628e6dd7597b042117

Now the problem even after changing this logical it still fails.
My modified pnpm version would assume to be:
https://gist.github.com/Jarrodsz/13fd50d2eb93914fec560e4364fec650

The problem is i seem to need to copy the package-lock.YAML file from the root of the mono repro, since it is not generated in my /mono_repro/apps/myapp/ folder.

GPT comes up with all kinds of obscure solutions not working.

What would be the correct way to gave an easy workflow for this?
I would like to just do a git push dokku master like im used to.

Is there way to generate the package-lock.yaml in the app folders somehow?
After 2 hours fiddling with the Dockerfile doing 100 deploys to test it and debug it I give up this is cybersome.

**Comment by PhilDL** [comment]
Hi, sorry but I am a bit lost, I never used Dokku and assumed it was a using standard Docker images. Some general advice:

- You shouldn't mix npm and pnpm in your Dockerfile, if you have a problem with the way pnpm installs dependencies you could add a `.npmrc` at the root of the project with:

```sh
prefer-workspace-packages=true
node-linker=hoisted
strict-peer-dependencies=false
auto-install-peers = true
```
- I insist but every command should be run from the root of the folder.
- If a command target a specific app in the monorepo you should use `--filter=@org/nameofthepackage`
- If you move around deps, your pnpm lock file could be out of sync, to fix that, from the root of your monorepo run `pnpm i --fix-lockfile`
- Turbo repo helps you build folder structure for Docker and correct package.json for the target app with `turbo prune --scope=@remix-gospel-stack/remix-app --docker` notice the `--docker` flag.
- I feel that you are reinventing the wheel yes, the tools like pnpm and turborepo should actually help you.
- If you feel that you begin to do too much outlandish stuff I would suggest you to recreate a simple monorepo that works with Dokku (if that's what you want), a simple empty Remix app, and just 1 package. Then slowly add complexity and see what the blocking points are, eventually, you would copy-paste every other packages you have in your repo and see when it begins to break.

Cannot help you more without looking into the whole project and trying for myself sorry!

**Comment by PhilDL** [comment]
I understand your frustration but it's really hard to help you without seeing the full code, environment, etc... that I could pull and run locally.

Let's put dokku out of the equation for a moment, **can you confirm that building AND running the Dockerfile locally works?**
I mean running local commands that are similar to that (switching for your database, and your docker network)

```bash
docker build -t remix-gospel-stack-remix-app -f ./apps/remix-app/Dockerfile .
docker run -it --init --rm -p 3000:3000 --env-file .env.docker --env DATABASE_URL='postgresql://postgres:postgres@db:5432/postgres' --network=app_network remix-gospel-stack-remix-app
```
