### ISSUE TITLE
App not reflecting UI changes directly | needs to do page refresh to see UI changes

### ISSUE THREAD

**Issue by Mat-moran** [PhilDL/remix-gospel-stack#60]
Hi, 

I was digging on how to set up a monorepo with remix and this appears, thanks for sharing your work men! 😄 

I notice that I can not see the UI modifications until I refresh the page. I tryed also running a modified instance of Epic-Stack  inside the monorepo and the same happened. This was very strange because I was using the same app outside the monorepo without problems. 

I saw that you are using your own server to launch remix (probably due to ESM?) and you are using `--manual` command during launch. This means that the problem probably comes from there right?

I think it is related with that because I  tryed with a plain `npx create-remix@latest` and it works fine, except if I use the command `--manual` in the package.json`"dev": "remix dev --manual"`. If I use this the behaveour is more or less the same, you lost Hot reloads and needs to do a complete refresh of the page to see the changes.

Can you confirm if you are suffering the same problem?? (maybe due to latest remix versions?) Thanks 😄

**Comment by PhilDL** [comment]
Hello, I don't have that problem sorry, this is my experience with this repo without modification: 
_(that GIF is heavy sorry)_

![remix-gospel-stack-hmr](https://github.com/PhilDL/remix-gospel-stack/assets/4941205/ac939be8-bfd7-464a-936f-3b9ce467906d)


On that gif, I run `pnpm dev --filter=@remix-gospel-stack/remix-app...` from the **root of the repository** to work only on the Remix app and its dependencies. Then I modify the default export of a route and a button Component in the `ui` package.

So I would need more info:
- What command are you running for your dev server and from where?
- What exactly are you modifying (some Tailwind classes, some React Components?)

If it's a Tailwind problem, your tailwind config file needs to watch the correct packages, you can see it from the `tailwind.config.ts` of the remix app.

If you have a UI package outside of the remix app and you need the server to pick up updates you will need to update your `remix.config.js` and add the relative path of that package to the `watchPaths` array (as in that monorepo).

Yes the server in this repo is custom, heavily copied from the epic-stack version 😅

**Comment by basselAhmed** [comment]
@PhilDL Updating shadcn-plugin.ts to add/change colors or any config, it doesn't reflect in the app till I do a full restart of the dev server, any idea why this might be happening?

**Comment by PhilDL** [comment]
@basselAhmed Unfortunately I haven't figured that out yet. `shadcn-plugin.ts` is built into the `packages/ui/dist/tailwind/index.mjs` file but then the tailwind plugin from remix cannot pick up modification to that file. Even if you explicitly put that file in watchPath of remix.config or `content` array of tailwind.config.ts.

If you find a solution I will gladly accept a pull request.

**Comment by basselAhmed** [comment]
@PhilDL I haven't figured out a proper solution but I did find a workaround that works for me for now.

in `tailwind.config.ts` in remix app
I imported the shadcn plugin file explicitly by relative path and passing it as plugin. this is not ideal but it works 🤷🏽 

```ts
import type { Config } from "tailwindcss";

import { shadcnPreset } from "@purpose/ui/tailwind";

import { shadcnPlugin } from "../../packages/ui/src/tailwind/shadcn-plugin.ts";

export default {
  content: [
    "src/**/*.{ts,tsx}",
    "./app/**/*.{ts,jsx,tsx}",
    "components/**/*.{ts,tsx}",
    "../../packages/**/*.{ts,tsx}",
  ],
  presets: [shadcnPreset],
  plugins: [shadcnPlugin],
} satisfies Config;
```
