### ISSUE TITLE
merge all dotenv files to one

### ISSUE THREAD

**Issue by chiptus** [PhilDL/remix-gospel-stack#70]
First, thanks for the work done in this repo. examples help me a lot, my current monorepo structure is based on this repo.

I recently ran into a problem with `packages/database` that required to have .env file inside the package. It might be some mistake on my side (I keep using pnpm from the root folder)

I saw in the readme that we should have `.env.docker` as well.

Am I doing anything wrong?

I would love to find a way to merge them all together. it's weird because I don't know where I should make a change

**Comment by PhilDL** [comment]
Hello! Thank you for your kind words.

## 1) The `.env.docker` 

This file is not required and only used if you want to run your built docker image locally, see it from the root `package.json` file:

```json
"docker:run:remix-app": "docker run -it --init --rm -p 3000:3000 --env-file .env.docker --env DATABASE_URL='postgresql://postgres:postgres@db:5432/postgres' --network=app_network remix-gospel-stack-remix-app",
```

`.env.docker` is passed to the `--env-file` when running the docker image. So in the end you may not need it at all.

## 2) Consolidating `.env` files for `packages/database`.

Yes `packages/database` **require the DATABASE_URL for prisma**, normally the `.env` in `packages/database` is a **symlink** of the root `.env` if you lost that symlink it will create problem. 

### Solution 1
You should check if the symlink is still present

```shell
ls -ltrah packages/database/.env
lrwxr-xr-x  1 yourusername  staff    10B 17 sep  2022 packages/database/.env -> ../../.env
```

Feel free to recreate the symlink:

```
ln -s ~/Code/remix-gospel-stack/.env ~/Code/remix-gospel-stack/packages/database/.env
```

### Solution 2

An alternative would be to install the `dotenv` npm package and modify the `packages/database` scripts like that:

```json
    "db:migrate:deploy": "pnpm with-env prisma migrate deploy",
    "db:migrate:dev": "pnpm with-env prisma migrate dev",
    "db:push": "pnpm with-env prisma db push",
    "db:seed": "tsx src/seed.ts",
    "db:migrate:force": "pnpm with-env prisma migrate reset --force",
    "with-env": "dotenv -e ../../.env.local --"
```

Notice the `with-env` line that uses the relative path of the root `.env` file. 
I tested something like that before and it worked but I decided to not include it in that example. 

Feel free to update the other scripts necessary in the same fashion and tell me if that would solve your problems!
